# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ministry_of_state}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hemant Kumar"]
  s.date = %q{2011-07-01}
  s.description = %q{A ActiveRecord plugin for working with state machines}
  s.email = %q{hkumar@crri.co.in}
  s.extra_rdoc_files = [ "LICENSE.txt", "README.rdoc" ]
  s.files = Dir.glob("*") + Dir.glob("test/*") + Dir.glob("lib/**/*")
  s.homepage = %q{http://github.com/gnufied/ministry_of_state}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Handling state machines}
  s.test_files = Dir.glob("test/*.rb")

  s.specification_version = 3

  s.add_runtime_dependency(%q<rails>, [">= 3.0.3"])
  s.add_development_dependency(%q<sqlite3>, [">= 0"])
  s.add_development_dependency(%q<shoulda>, [">= 0"])
  s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
end
